export const userTypes = {
  SIGN_IN_WITH_EMAIL_REQUEST: 'SIGN_IN_WITH_EMAIL_REQUEST,',
  SIGN_IN_WITH_EMAIL_SUCCESS: 'SIGN_IN_WITH_EMAIL_SUCCESS,',
  SIGN_IN_WITH_EMAIL_FAIL: 'SIGN_IN_WITH_EMAIL_FAIL,',
};
