export const userTypes = {
  SIGN_IN_WITH_EMAIL_REQUEST: 'SIGN_IN_WITH_EMAIL_REQUEST,',
  SIGN_IN_WITH_EMAIL_SUCCESS: 'SIGN_IN_WITH_EMAIL_SUCCESS,',
  SIGN_IN_WITH_EMAIL_FAIL: 'SIGN_IN_WITH_EMAIL_FAIL,',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST,',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS,',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL,',
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST,',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS,',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL,',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION,',
};
